name: Control
description: Controlling issue.  May be split into sub-tasks
projects: "prjtest"
body:
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Business requirements to be met at the end of the project
      value: "- [ ]"
  - type: textarea
    id: milestones
    attributes:
      label: Business milestones
      description: Relevant business milestones
